### ISSUE TITLE
Executing the program

### ISSUE THREAD

**Issue by sameer9406** [yangbai90/jLIBs#1]
can we execute this program and look at the results?

**Comment by yangbai90** [comment]
Hi @sameer9406 , now the P2D model is still under development. For each folder, it contains individual Julia script, which means if you have installed the Julia environment, you can run it from your terminal.

For example, in the Cahn-Hilliard folder, we have a ch1d.jl script. Then we can run it from the terminal:
`julia ch1d.jl`

To better visualize the result, I suggest our user use the [Atom](https://atom.io/) editor, once the Julia plugin is installed, you should see the result in Atom immediately.

**Comment by sameer9406** [comment]
Thanks a lot @yangbai90.
